{% set version = "0.1.3" %}

package:
  name: parq2csv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/parq2csv/parq2csv-{{ version }}.tar.gz
  sha256: a91bcdb08214ef36fdd2593743d01edc117cdaeb8d3f85bea1e8f952929f62f7

build:
  entry_points:
    - parq2csv = parq2csv.main:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - pyarrow

test:
  imports:
    - parq2csv
  commands:
    - pip check
    - parq2csv --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mludv/parq2csv
  summary: Command line tool to transform Apache Parquet files to CSV on the go
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
